---
# Source: prometheus/templates/alertmanager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: infra
    chart: prometheus-8.4.6
    heritage: Tiller
  name: infra-prometheus-alertmanager